project_id = "mzikfyqzwepnubdsclfd"

[functions.get-google-maps-key]
verify_jwt = false

[functions.mapbox-token]
verify_jwt = false

[functions.google-solar-api]
verify_jwt = false

[functions.send-quote-email]
verify_jwt = false

[functions.fetch-solar-asset]
verify_jwt = false