project_id = "mzikfyqzwepnubdsclfd"

[functions.solar-map]
verify_jwt = false

[functions.solar-map-image]
verify_jwt = false

[functions.solar-analysis]
verify_jwt = false

[functions.submit-lead]
verify_jwt = false

[functions.isabella-orchestrator]
verify_jwt = false
